<?php

namespace deduar\S3SandBoxBundle\Repository;

/**
 * ExcepcionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExcepcionRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllOrderedByName($idSup,$criteria,$direc)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT e FROM S3SandBoxBundle:Excepcion e 
            	WHERE e.idempleado = '.$idSup.' ORDER BY e.'.$criteria.' '.$direc)
            ->getResult();
    }

}
